### ISSUE TITLE
Unused Variable

### ISSUE THREAD

**Issue by erincatto** [BobbyAnguelov/Esoterica#10]
https://github.com/BobbyAnguelov/Esoterica/blob/392927cf316148e08f119043b5fc9ac3e7e2adfd/Code/Engine/Animation/Graph/Nodes/Animation_RuntimeGraphNode_Transition.cpp#L294

Jetbrains Resharper does a nice coloring to show unused variables.

**Comment by BobbyAnguelov** [comment]
I've only ever had bad experiences with Resharper locking up VS. 

I'll try to re-enable the compiler warning for things like that. I realize that a lot of changes have happened with the warning levels in recent VS versions so will play around with those settings.

**Comment by BobbyAnguelov** [comment]
It's fixed plus dozen instances. Also increased warning level to ALL and fixed a bunch of lesser bugs that the increased warnings caught. Not sure when L4 became so lax.
