### ISSUE TITLE
Animation Graph Crashes on Parameter Renaming

### ISSUE THREAD

**Issue by yxsamurai** [BobbyAnguelov/Esoterica#15]
hi, I encountered a crash issue caused by parameter node renaming.
Below is the source code in AnimationGraphWorkspace::RenameParameter function
it should be " if (pControlParameter != nullptr) "
![param_renaming_issue](https://user-images.githubusercontent.com/17874737/199874844-30560e3b-05bc-475d-a6df-c32a2d64acda.png)

**Comment by BobbyAnguelov** [comment]
🤦‍♂️

Fixed... will try to push it and several more fixes later today. Thanks for the report!
