### ISSUE TITLE
Min/Max not needed for LCM

### ISSUE THREAD

**Issue by erincatto** [BobbyAnguelov/Esoterica#18]
https://github.com/BobbyAnguelov/Esoterica/blob/2f82fe8e7f99cae380dd1661e979a477e54803ec/Code/Engine/Animation/AnimationSyncTrack.cpp#L71

https://en.wikipedia.org/wiki/Least_common_multiple

**Comment by BobbyAnguelov** [comment]
yeh, that's a dumb typo, probably a copy/paste or refactoring error.
