### ISSUE TITLE
Wrong Arguments

### ISSUE THREAD

**Issue by erincatto** [BobbyAnguelov/Esoterica#19]
https://github.com/BobbyAnguelov/Esoterica/blob/8486c6099b383a3761d82c1cfda8da839786e4a6/Code/Engine/Animation/Graph/Nodes/Animation_RuntimeGraphNode_Vectors.cpp#L106

**Comment by erincatto** [comment]
Well the second one is wrong.

**Comment by BobbyAnguelov** [comment]
Whoops! Thanks. Have fixed it but I have some larger changes that I'm still testing so I'll push hopefully later this weekend!
