### ISSUE TITLE
Member order optimization

### ISSUE THREAD

**Issue by erincatto** [BobbyAnguelov/Esoterica#2]
Consider ordering members based on size: largest to smallest. This often reduces padding thus reducing memory usage and improving cache efficiency. I think I have seen this in a few spots, here is one:

https://github.com/BobbyAnguelov/Esoterica/blob/9aef24921058a8322f6dffcfe152265ba91f9d08/Code/Engine/Animation/Graph/Animation_RuntimeGraph_RootMotionDebugger.h#L50

Minor issue.

**Comment by BobbyAnguelov** [comment]
I'm already doing that using the StructLayout tool. That said I've mostly cared about the runtime code and have been more lax on the debug tools side. In this case though, it doesnt matter how I shift the variables around the memory size is unchanged:

![image](https://user-images.githubusercontent.com/10767490/185700451-18208544-31fd-4f6e-90e7-6563e3a1b3e6.png)
