### ISSUE TITLE
Issue Building Esoterica

### ISSUE THREAD

**Issue by RemiVerlinden** [BobbyAnguelov/Esoterica#21]
I have been trying to get Esoterica to compile with the 5 step plan, but I am getting build errors at step 4.
<sub>REBUILD the "Esoterica.Scripts.Reflect" project (under the "0. Scripts" solution folder) - this will generate all the Esoterica reflection data.</sub>

I've added the build log as attachment.

I am still a novice at this sort of stuff so I apologise for the inconvenience.
 
[Output-Build.txt](https://github.com/BobbyAnguelov/Esoterica/files/10852727/Output-Build.txt)

**Comment by BobbyAnguelov** [comment]
Did you download the external data package and extract that into the correct folder?

In your case:  C:\GitHub\Esoterica\External

**Comment by RemiVerlinden** [comment]
Here is a screenshot of my files structure, it should be correct.

<img width="585" alt="Esoterica-File-Structure" src="https://user-images.githubusercontent.com/97361273/222142323-9ae93814-7fad-46fe-ae48-90a99c8d1cb5.png">

**Comment by BobbyAnguelov** [comment]
And can you check that you havent accidentally created a External/External folder when unzipping?

You should have the clang stuff in this folder: C:\GitHub\Esoterica\External\LLVM\

**Comment by RemiVerlinden** [comment]
Here is a picture of the LLVM subfolder.

<img width="610" alt="Esoterica-Double-Extract" src="https://user-images.githubusercontent.com/97361273/222281656-af68f723-1058-4904-82c3-75f50f623c7f.png">

**Comment by RemiVerlinden** [comment]
I believe I have found something that could be useful.
I was previously unaware that it was possible to set various logging levels on the build tool. 
To provide more information, I have included a build log where the "MSBuild project build log verbosity" is set to Diagnostic.

[Esoterica.Scripts.Reflect.log](https://github.com/BobbyAnguelov/Esoterica/files/10866310/Esoterica.Scripts.Reflect.log)

**Comment by BobbyAnguelov** [comment]
I did some quick searching and I think you're using a version of VS 2022 that's too old. I think I compiled the LLVM libs with VS 2022 17.4. What version of VS 2022 are you using? I'm assuming you're on <17.3?

I'll see if I can find some time this weekend to recompile LLVM with an older VS 2022 version and provide those binaries but for now I think you can just upgrade your VS version and everything should be fine?

**Comment by RemiVerlinden** [comment]
You are correct, the issue was related to the version of Visual Studio 2022 that I was using. Upgrading to a newer version resolved the problem.
I must admit that I feel a bit foolish for not realizing sooner that the problem was related to my version of VS22.
Thank you for looking into this. I appreciate your effort. 🙂
