### ISSUE TITLE
Sync Event Index Condition Pin Type

### ISSUE THREAD

**Issue by erincatto** [BobbyAnguelov/Esoterica#23]
https://github.com/BobbyAnguelov/Esoterica/blob/a30f2bbd08085006290e67ca8edcdc92a5d1d723/Code/EngineTools/Animation/ToolsGraph/Nodes/Animation_ToolsGraphNode_Events.cpp#L200

Should be `bool`?

**Comment by BobbyAnguelov** [comment]
yup... stupid typo! also fixed in the plastic depot.
