### ISSUE TITLE
Update from your newest ExternalData but found an invalid lib.

### ISSUE THREAD

**Issue by Catddly** [BobbyAnguelov/Esoterica#28]
When i compile your latest version which is merged from you as upstream, i update my projects entirely.

While building the Reflector application, i got this error from VS:
LLVMCore.lib(DataLayout.obj) : error LNK2019: unresolved external symbol __std_max_element_1 referenced in function "unsigned char const * __cdecl __std_max_element<unsigned char const >(unsigned char const *,unsigned char const *)" (??$__std_max_element@$$CBE@@YAPEBEPEBE0@Z) [C:\Users\Admin\Documents\GitHub\Esoterica\Code\Applications\Reflector\Esoterica.Applications.Reflector.vcxproj]

It seems that it can NOT find the definition of __std_max_element() from the library LLVMCore.lib.

It the version of LLVMCore.lib incorrect or something else cause this bug?

Thanks for your helping!!

**Comment by Catddly** [comment]
I try to dump the symbols in LLVMCore.lib using Visual Studio Command Prompt, it seems that __std_max_element_1 is NOT correctly decorated.

See this screenshot below:
![image](https://github.com/BobbyAnguelov/Esoterica/assets/57090275/b08a6b5a-1b39-4acc-b4ed-0575a17fbe76)

But it is there inside the LLVMCore.lib, why the linker can not find the symbol??

**Comment by BobbyAnguelov** [comment]
What version of VS are you using to compile. Someone had a similar problem and it turned out they were using an older VS. 

You need VS2022 17.6 or later.

**Comment by Catddly** [comment]
Oh! I am using Visual Studio 2022 17.4, i will update it and see if this problem still exists.

**Comment by Catddly** [comment]
By the way, did you know this file? I can't find it in your latest project: 

![image](https://github.com/BobbyAnguelov/Esoterica/assets/57090275/09ea14f4-d1ca-486d-b0ea-45ddd0dfce73)

Its name is Engine.Tools.Core.PropertyGrid.PropertyGridCoreEditors.h

**Comment by BobbyAnguelov** [comment]
Hm... that's strange. Let me check the state of the github after work. It actually a mirror from my actual working repo that I update with a script, something might have gone wrong in the last update.

**Comment by BobbyAnguelov** [comment]
Okay, I pushed the latest version of the engine + an updated external data archive. Can you try again with the new version...

**Comment by Catddly** [comment]
Sorry i had been a little bit busy.

I already merged your latest branch but i haven't test it yet. I think it will be ok.

I am trying to integrate a Vulkan Backend and Render Graph System into your Engine.
I think your engine's framework is very elegant and i am learning from it too.
But i am just new to game developping and i think my code will not be ready to be used at soon (at least for now).

Thanks for your help!

**Comment by Catddly** [comment]
Sorry i had been a little bit busy. I am just graduated and start to work, it is a total mess.

I already merged your latest branch but i haven't test it yet. I think it will be ok and i will test it when i have some time.

I am trying to integrate a Vulkan Backend and Render Graph System into your Engine and try to maximize the multi-threading power of your engine framework and some other new attempts. This is also a challenge to me.
I think your engine's framework is very elegant and i am learning from it too.
However i am just new to game developping and i think my code will not be ready to integrate to your master branch, i will just test on my own branch.

Thanks for your help! Thanks for sharing this Esoterica.

**Comment by Catddly** [comment]
Sorry i had been a little bit busy. I am just graduated and start to work, it is a total mess.

I already merged your latest branch but i haven't test it yet. I think it will be ok and i will test it when i have some time.

I am trying to integrate a Vulkan Backend and Render Graph System into your Engine and try to maximize the multi-threading power of your engine framework and some other new attempts. This is also a challenge to me.
I think your engine's framework is very elegant and i am learning from it too.
However i am just new to game developping and i think my code will not be ready to integrate to your master branch, i will just test on my own branch.

Thanks for your help! Thanks for sharing Esoterica.
