### ISSUE TITLE
Assertion in Editor Application in EditorUI::DrawEditorToolContents no longer persists.

### ISSUE THREAD

**Issue by Catddly** [BobbyAnguelov/Esoterica#29]
Assertion break when i launch the merged and resolved version of your newest commit.

![image](https://github.com/BobbyAnguelov/Esoterica/assets/57090275/2b9a2081-c337-463d-b4a5-21581414c0fa)

The begin count is no longer 2 and can vary from 2 to 4.
But it seems that it has no observable effects on using the Editor as i comment this line of assertion.

**Comment by BobbyAnguelov** [comment]
That should be fixed. I've been doing a bunch of reworking of the editor tools and am unfortunately pushing some untested versions to github as some folks are asking for it.

**Comment by BobbyAnguelov** [comment]
I've just pushed the latest state of the engine and tested it, this shouldn't be happening any more
