### ISSUE TITLE
Variation Editor working?

### ISSUE THREAD

**Issue by erincatto** [BobbyAnguelov/Esoterica#3]
I'm able to create variations but I seem unable to modify the entries.

**Comment by BobbyAnguelov** [comment]
Yeh, I need to rework the resource picker widget (currently it's all sorts of hacked). It's one of the next things on my list of things to improve...

![image](https://user-images.githubusercontent.com/10767490/185756811-e6504dd9-e50f-4e26-bc15-9ee14aa09fb9.png)

Will try get to it this week!

**Comment by BobbyAnguelov** [comment]
Actually took a look at the code and there was a typo, it's fixed now but I'll still give it a good once over this week!
