### ISSUE TITLE
External Zip File should update

### ISSUE THREAD

**Issue by the-loki** [BobbyAnguelov/Esoterica#31]
some dep like ISPCTextureCompressor not found in it.

**Comment by BobbyAnguelov** [comment]
Ah yeh, that's my bad. I'm currently on vacation but will try to update it as soon as possible. 

Sorry about that.

**Comment by mctb32** [comment]
I think I've run into the same issue. At first I had an error opening <DirectXTex.h> in ResourceCompiler_RenderTexture.cpp, but I found it included in the externals so I switched to a relative path. But now I'm getting error opening <ispc_texcomp.h> in the same cpp and this one is not included in the externals.

**Comment by BobbyAnguelov** [comment]
Yeh, I recently switched from directxtex to ispc texture compressor and forgot to update the dependencies. 

I'm flying back from my vacation today so I'll try to update it tomorrow evening after work.

**Comment by BobbyAnguelov** [comment]
ExternalData.zip should be updated. Let me know if there's any issues.

I need to find a better way to manage this...
