### ISSUE TITLE
How Build? Please!!!!!!

### ISSUE THREAD

**Issue by 061999** [BobbyAnguelov/Esoterica#34]

**Comment by CitroenGames** [comment]
https://github.com/BobbyAnguelov/Esoterica?tab=readme-ov-file#building-esoterica

**Comment by ved-fy** [comment]
Does these instructions still work? Last month I followed this and didn't have much luck.

**Comment by ved-fy** [comment]
If someone here or Bobby knows how to build these llvm binaries, it would be great help. I been trying to build the 17.0.3 version to get it to work on latest Visual Studio version. But sadly I am not able to compile it at all.

**Comment by BobbyAnguelov** [comment]
Sorry for the delayed response. I've been dealing with some personal issues. 

I've updated the code and the dependency archive to work with the latest VS version 17.11.5. This will resolve the LLVM/clang issues.
