### ISSUE TITLE
Crash in MeshCompiler::TransferMeshGeometry

### ISSUE THREAD

**Issue by dimetcm** [BobbyAnguelov/Esoterica#37]
I'm trying to use fbx assets from  [Amazon Lumberyard Bistro](https://developer.nvidia.com/orca/amazon-lumberyard-bistro) and getting a crash in `MeshCompiler::TransferMeshGeometry`. Basically geometry section has two channels, but vertex has only one pair of texture coordinates.

![image](https://github.com/user-attachments/assets/a1a4dcb1-936f-4333-9b59-4d19a5971691)

It happens because of **BistroInterior_Wine.fbx** has one material that used by several meshes with different amount of uv channels and when those meshes are being merged by material that is not taken into account.

There is my naive [fix](https://github.com/dimetcm/Esoterica/commit/51060234f98730ed0bacb94d2ee70870034fd1df) for that, please take a look if it makes sense.

**Comment by BobbyAnguelov** [comment]
Will integrate that into our rendering branch since the mesh importer is significantly different there, will see if I can port some of that back to main

**Comment by BobbyAnguelov** [comment]
Makes sense, I've prepped it so that we can add more qualifiers for merging.
