### ISSUE TITLE
Changed FreeLookCamera FocusOn behavior. Focus camera on entity when user double clicks in the entity editor outliner.

### ISSUE THREAD

**Issue by dimetcm** [BobbyAnguelov/Esoterica#39]
As per title, maybe it's something that you'll be interested in pushing to the main?
CL 01bb33a6245df059cbfae9143e9a5d15949defaa. Camera focus takes into account the entity's bounds, so they all fit in the view.

**Comment by BobbyAnguelov** [comment]
Thanks will integrate this.

**Comment by BobbyAnguelov** [comment]
Thanks, integrated this!
