### ISSUE TITLE
Live++ Bridge enabled

### ISSUE THREAD

**Issue by jason-SEMCdev** [BobbyAnguelov/Esoterica#5]
Default configuration seems to still want to run un-licensed Live++:

![image](https://user-images.githubusercontent.com/108023385/186717161-2cd05c6f-59fa-4de8-ba51-520207f3fead.png)

LivePP.props seems to have:
`<LPP_INCLUDED>True</LPP_INCLUDED>`

I'll fork and submit pull requests.

**Comment by BobbyAnguelov** [comment]
oh, I'll disable that... I don't use git at home so I have a script that backs up to git and I guess I accidentally pushed that

**Comment by BobbyAnguelov** [comment]
Fixed!
