### ISSUE TITLE
Missing resource in log when starting editor (prototype_3cs_minimal.map)

### ISSUE THREAD

**Issue by gordeevso** [BobbyAnguelov/Esoterica#7]
I followed the instructions and put data as said in the description, but got this message:

**Error: Source file (D:\Projects\Esoterica\Data\maps\prototype_3cs_minimal.map) doesnt exist!**

Seems like it is supposed to be in EsotericaData.7z, but not sure about it. Am I missing something?

**Comment by BobbyAnguelov** [comment]
Oh, that's because I submitted the .user files with the commandline args still set...

I'll see about excluding those file. For now, just clear the debugger startup arg and it's fine.
